In [1]:
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN
import numpy as np

c:\Users\davis\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [50]:
import re
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [2]:
df = pd.read_csv('synthetic_logs.csv')
df.head()

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert

In [3]:
df = df.drop(['complexity'], axis = 1)

In [4]:
df.head()

,timestamp,source,log_message,target_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status

In [5]:
df.source.unique()

<ArrowStringArray>
[      'ModernCRM', 'AnalyticsEngine',        'ModernHR',   'BillingSystem',
   'ThirdPartyAPI',       'LegacyCRM']
Length: 6, dtype: str

In [6]:
df.target_label.unique()

<ArrowStringArray>
[        'HTTP Status',      'Critical Error',      'Security Alert',
               'Error', 'System Notification',      'Resource Usage',
         'User Action',      'Workflow Error', 'Deprecation Warning']
Length: 9, dtype: str

In [7]:
#Load pre-trained sentence transformer model
model = SentenceTransformer('all-MiniLM-L6-v2') #384 dims

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2161.96it/s]

In [8]:
#Generate embeddings for log messages
embeddings = model.encode(df['log_message'].tolist())

In [33]:
#clustering
dbscan = DBSCAN(eps=0.2, min_samples=4, metric='cosine')
clusters = dbscan.fit_predict(embeddings)

In [34]:
df['cluster'] = clusters
df.head()

,timestamp,source,log_message,target_label,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0,NaN
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1,NaN
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,-1,NaN
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0,NaN
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,0,NaN

In [35]:
df.cluster.unique()

array([ 0,  1, -1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 19, 13, 14,
       15, 16, 17, 18, 22, 20, 21, 27, 33, 32, 24, 23, 31, 25, 26, 28, 29,
       30, 37, 35, 34, 36], dtype=int64)

In [36]:
df[df.cluster == 1].head()

,timestamp,source,log_message,target_label,cluster,regex_label
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1,NaN
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,1,NaN
217,1/22/2025 5:45,BillingSystem,Mail service encountered a delivery glitch,Error,1,NaN
248,5/2/2025 23:04,ModernHR,Service disruption caused by email sending error,Critical Error,1,NaN
265,3/30/2025 23:53,ModernCRM,Email system had a problem sending emails,Error,1,NaN

In [37]:
def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (in|out)." : "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message, re.IGNORECASE):
            return label
        return None

In [38]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)
df

,timestamp,source,log_message,target_label,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0,NaN
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1,NaN
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,-1,NaN
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0,NaN
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,0,NaN
...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,0,NaN
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,6,NaN
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,0,NaN
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,1,NaN
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,6,NaN

In [39]:
df[df.regex_label.isna()]

,timestamp,source,log_message,target_label,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0,NaN
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1,NaN
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,-1,NaN
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0,NaN
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,0,NaN
...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,0,NaN
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,6,NaN
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,0,NaN
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,1,NaN
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,6,NaN

In [43]:
df[df.regex_label.notnull()]

,timestamp,source,log_message,target_label,cluster,regex_label
27,9/24/2025 19:57,ThirdPartyAPI,User User685 logged out.,User Action,10,User Action
57,9/14/2025 3:03,AnalyticsEngine,User User395 logged in.,User Action,10,User Action
85,3/13/2025 2:11,ModernHR,User User225 logged in.,User Action,10,User Action
88,3/8/2025 19:04,AnalyticsEngine,User User494 logged out.,User Action,10,User Action
126,11/22/2025 21:09,ThirdPartyAPI,User User900 logged in.,User Action,10,User Action
...,...,...,...,...,...,...
2207,10/4/2025 8:06,ModernCRM,User User495 logged in.,User Action,10,User Action
2263,2/27/2025 14:40,AnalyticsEngine,User User429 logged out.,User Action,10,User Action
2275,3/13/2025 17:17,AnalyticsEngine,User User755 logged out.,User Action,10,User Action
2323,12/1/2025 18:17,ThirdPartyAPI,User User882 logged out.,User Action,10,User Action
2353,6/10/2025 19:38,AnalyticsEngine,User User536 logged in.,User Action,10,User Action

In [ ]:
df_non_regex = df[df['regex_label'].isnull()].copy()
df_non_regex

,timestamp,source,log_message,target_label,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0,NaN
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1,NaN
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,-1,NaN
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0,NaN
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,0,NaN
...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,0,NaN
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,6,NaN
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,0,NaN
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,1,NaN
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,6,NaN

#BERT & Logistic Regression

In [46]:
print(df_non_regex['target_label'].value_counts() < 5)

target_label
HTTP Status            False
Security Alert         False
System Notification    False
Error                  False
Resource Usage         False
Critical Error         False
User Action            False
Workflow Error          True
Deprecation Warning     True
Name: count, dtype: bool

In [47]:
df_non_legacy = df_non_regex[df_non_regex.source!='LegacyCRM']
df_non_legacy.source.unique()

<ArrowStringArray>
['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem', 'ThirdPartyAPI']
Length: 5, dtype: str

In [48]:
#Generate embeddings
filtered_embeddings = model.encode(df_non_legacy['log_message'].tolist())
filtered_embeddings[:2]

array([[-1.02939621e-01,  3.35459746e-02, -2.20260657e-02,
         1.55103824e-03, -9.86923277e-03, -1.78956226e-01,
        -6.34409934e-02, -6.01761825e-02,  2.81108972e-02,
         5.99620566e-02, -1.72618572e-02,  1.43363792e-03,
        -1.49559990e-01,  3.15284869e-03, -5.66030890e-02,
         2.71685496e-02, -1.49890315e-02, -3.54037844e-02,
        -3.62936445e-02, -1.45410709e-02, -5.61493682e-03,
         8.75539035e-02,  4.55120690e-02,  2.50963699e-02,
         1.00187613e-02,  1.24266930e-02, -1.39923617e-01,
         7.68696293e-02,  3.14095132e-02, -4.15246096e-03,
         4.36902680e-02,  1.71250124e-02, -8.00951198e-02,
         5.74005730e-02,  1.89092048e-02,  8.55262280e-02,
         3.96399312e-02, -1.34371847e-01, -1.44363393e-03,
         3.06707132e-03,  1.76854044e-01,  4.44888510e-03,
        -1.69274844e-02,  2.24266667e-02, -4.35049534e-02,
         6.09027408e-03, -9.98167042e-03, -6.23972490e-02,
         1.07372822e-02, -6.04895130e-03, -7.14660957e-02,
        -8.45804065e-03, -3.18019763e-02, -1.00518353e-01,
         2.25875570e-04, -1.89341232e-02, -3.17793936e-02,
         4.00861315e-02,  2.19178237e-02, -2.59528831e-02,
         5.84525093e-02, -8.12509879e-02,  2.12029237e-02,
        -5.02687544e-02,  1.32057332e-02,  1.32673478e-03,
         2.27062795e-02, -3.45793851e-02,  3.91546972e-02,
        -2.09433511e-02,  3.24822403e-03,  4.43960875e-02,
        -9.85357836e-02, -2.88895518e-02, -6.85021281e-03,
         5.38819171e-02,  6.46110028e-02, -2.45060567e-02,
         9.21828896e-02, -7.49868825e-02,  1.23994835e-02,
        -1.00026593e-01, -4.64910716e-02,  6.01570010e-02,
        -2.46480238e-02, -7.08076358e-02, -2.77270675e-02,
         9.72611159e-02,  3.85841615e-02, -1.44293280e-02,
        -7.46849983e-04, -1.04305297e-02, -1.61842927e-02,
         4.43627909e-02,  9.25996527e-03,  7.14165345e-02,
         6.37917444e-02,  4.94931079e-02, -6.02567382e-02,
         4.04805616e-02, -3.42860594e-02, -1.93881262e-02,
         6.61233962e-02,  6.01589456e-02,  1.09371310e-02,
        -5.38630085e-03,  1.44579699e-02,  9.25430059e-02,
        -3.14564481e-02, -1.84352025e-02,  9.91872977e-03,
        -1.85574144e-02,  1.31285703e-03,  2.26557531e-05,
         2.02736398e-03,  2.75256746e-02, -4.81927879e-02,
         5.42825982e-02, -7.32067153e-02,  4.88666929e-02,
         4.98490334e-02, -9.01146699e-03, -4.68905605e-02,
        -4.25886586e-02, -8.19523633e-02,  3.87106128e-02,
         7.85503611e-02,  1.46077081e-32,  1.66706555e-02,
         5.25494069e-02, -1.82448737e-02, -1.26686478e-02,
         6.52837232e-02, -2.11777538e-02, -4.06322777e-02,
         4.14947346e-02, -2.48361267e-02, -1.33068301e-02,
        -5.46753928e-02, -5.99128136e-04, -4.89245960e-03,
        -6.27359524e-02, -3.84878181e-02, -6.13543615e-02,
         8.27405155e-02,  2.34379917e-02, -8.63090158e-03,
         1.31003009e-02,  6.44214898e-02, -4.41361777e-02,
        -6.98633343e-02, -7.36060441e-02, -4.33264002e-02,
         6.96522743e-03, -5.05956635e-02, -1.60911959e-02,
        -5.66794164e-02,  3.35454987e-03,  5.34115098e-02,
         2.47761216e-02, -1.47985956e-02, -2.93243285e-02,
         7.30227903e-02, -1.86833851e-02,  8.13137069e-02,
        -2.69967448e-02, -5.68056367e-02, -6.59389049e-02,
        -5.95394522e-03,  2.85312999e-02, -7.85357952e-02,
        -2.76696240e-03, -3.26467236e-03, -9.28333104e-02,
        -7.27362931e-02, -3.31903584e-02,  1.01411097e-01,
         9.79881957e-02, -9.78740379e-02,  1.98667701e-02,
         2.38837395e-02, -1.81672759e-02, -3.73708904e-02,
         1.96552300e-03,  6.34426028e-02,  1.18271643e-02,
        -1.12041309e-02, -3.87316234e-02,  9.32423994e-02,
         4.26630862e-03, -1.66872665e-02, -6.87464401e-02,
         1.55120073e-02, -4.97755110e-02,  3.34493406e-02,
         8.00032318e-02,  2.12282166e-02,  1.34581909e-01,
        -2.30729654e-02,  5.53859062e-02,  3.07558365e-02,
        -2.93905418e-02,  2.31905561e-02, -9.34307873e-02,
         7.58034959e-02, -5.21204667e-03, -5.14523201e-02,
         3.32689136e-02,  3.67963389e-02, -1.06450338e-02,
         1.01634879e-02, -2.07651276e-02, -5.85519038e-02,
         4.79328372e-02,  2.13694908e-02,  8.76213238e-02,
         3.35493451e-03, -3.80336456e-02, -1.81205366e-02,
         6.87448401e-03,  5.15879802e-02, -4.75598536e-02,
        -6.12065010e-02, -1.45483604e-32,  4.12801048e-03,
         4.59640939e-03, -5.63900582e-02,  4.32464760e-03,
        -1.09443767e-03,  9.31957550e-03, -2.20269058e-02,
         5.79564236e-02, -1.44787328e-02,  4.64155637e-02,
         1.43542901e-01, -6.89756870e-02,  6.09631576e-02,
        -8.93743783e-02,  2.40919571e-02,  2.06010062e-02,
        -2.82415841e-02, -6.48315325e-02,  5.64795323e-02,
        -7.48339482e-03, -3.52058336e-02,  8.51060301e-02,
         1.30360033e-02,  2.02257857e-02, -1.44390957e-02,
        -4.63718884e-02,  1.77209843e-02,  1.59105826e-02,
        -9.51009691e-02, -3.54527161e-02,  2.08696425e-02,
         3.84386466e-03, -8.77918303e-02,  6.44575432e-02,
         1.44171212e-02,  3.84728122e-03,  4.70991507e-02,
         4.94661406e-02,  1.53862871e-02, -2.59578507e-02,
         9.10894647e-02,  1.83308031e-02, -5.89206256e-02,
         2.51992624e-02, -3.30374353e-02,  8.23345035e-02,
         1.74792316e-02,  6.48047328e-02, -1.19674085e-02,
        -3.31778601e-02,  3.00177783e-02,  3.54220010e-02,
        -1.39624560e-02,  6.69272766e-02,  3.87920439e-02,
         6.06916659e-02,  1.17958244e-03, -2.38786917e-02,
        -1.26930460e-01,  1.13846576e-02,  1.59290154e-02,
        -1.29426960e-02, -8.63247737e-02,  8.53661448e-03,
         6.03761077e-02,  1.51122082e-02, -1.19132377e-01,
         1.15234517e-02,  5.97089827e-02, -3.93345356e-02,
         1.55673195e-02,  1.04602007e-02, -4.72456552e-02,
        -2.59243250e-02,  9.98529606e-03,  3.07146572e-02,
        -7.14844689e-02,  6.98963273e-03, -1.55133335e-02,
         2.18863990e-02, -2.78146006e-02,  6.92733228e-02,
        -2.75903475e-02,  2.62429640e-02,  3.52562219e-02,
        -4.26419936e-02,  7.46301375e-04,  6.59866631e-02,
        -5.15105426e-02, -3.58433947e-02, -6.53442089e-03,
        -2.75858473e-02, -1.00125551e-01,  7.83326030e-02,
        -1.45798931e-02, -6.18457250e-08,  2.00325344e-02,
         6.59785271e-02, -2.04702597e-02,  1.64044090e-02,
         7.63001069e-02,  7.32182860e-02,  5.65787684e-03,
        -6.97804266e-04, -3.63796647e-03,  6.02394082e-02,
        -3.27186957e-02, -6.45838305e-02, -5.97952493e-02,
        -1.76696181e-02,  6.10138616e-03, -5.63489599e-03,
        -1.22972250e-01,  6.35818765e-02, -2.19431724e-02,
        -1.16406478e-01,  2.34366227e-02, -7.23525286e-02,
         2.31774058e-02, -6.55987188e-02, -7.42681623e-02,
         2.60146335e-02,  3.59758474e-02,  7.68432468e-02,
        -3.08057293e-02, -2.34793741e-02, -6.30426332e-02,
        -3.62158418e-02, -1.03560118e-02, -4.75601964e-02,
        -2.87522264e-02,  2.96400581e-02, -5.26895374e-03,
         5.67890257e-02, -3.74490907e-03,  3.09612900e-02,
         3.48227471e-02,  3.78607735e-02,  2.10155658e-02,
         2.70691570e-02,  5.25520518e-02,  7.16229528e-02,
        -5.53755136e-03,  4.01094332e-02,  5.16276620e-02,
        -2.67314557e-02,  5.94224408e-02, -4.29224297e-02,
        -1.19760577e-02,  3.05985045e-02, -7.40331486e-02,
         1.84222106e-02, -8.64863023e-03, -8.83557424e-02,
        -5.91984242e-02, -1.00898884e-04,  1.12913631e-01,
         4.57792450e-03, -4.25971672e-02,  3.22622061e-03],
       [ 8.04573111e-03, -3.57392319e-02,  4.93873693e-02,
        -7.19186431e-03,  6.17618731e-04, -9.05685276e-02,
         5.75595126e-02, -4.39446270e-02,  1.74751282e-02,
         5.21203168e-02, -4.62331995e-02,  2.49039624e-02,
         4.80811484e-02,  6.86636716e-02,  3.56146544e-02,
         3.00089661e-02,  2.61449628e-02, -9.05241370e-02,
        -8.02174136e-02,  5.04851379e-02, -7.90870711e-02,
        -1.76855875e-03, -2.48927325e-02,  9.02152732e-02,
         5.83695294e-03, -6.91071004e-02, -6.67965561e-02,
        -6.99114427e-03, -1.04565993e-01, -2.66474038e-02,
         3.05639878e-02,  2.02934444e-02,  2.25454420e-02,
        -4.22685500e-03,  1.11173335e-02,  6.78260699e-02,
         1.06073143e-02,  7.56635964e-02, -8.22778046e-02,
         8.45732260e-03, -6.97612166e-02, -4.21974398e-02,
        -1.05674909e-02,  2.23673265e-02,  5.64496815e-02,
         8.16501863e-03,  1.09344050e-01,  3.16565000e-02,
        -1.76923592e-02, -3.21071409e-02, -3.39975990e-02,
        -4.91835352e-04,  3.72877438e-03,  2.83771511e-02,
        -1.28521761e-02, -1.07932556e-03, -6.32418916e-02,
         6.89900666e-02,  1.77270640e-02, -5.20959757e-02,
         8.28307681e-03,  5.45033105e-02, -5.42099774e-02,
        -4.53332849e-02, -4.07493860e-02, -2.82698218e-02,
         1.23606184e-02, -2.13815942e-02, -2.36265566e-02,
         1.25317788e-02, -2.37170756e-02,  3.97411697e-02,
        -1.24362253e-01,  7.60625526e-02,  5.50834164e-02,
         8.28216746e-02,  2.97118798e-02, -1.84067376e-02,
        -1.96194891e-02,  5.54319173e-02, -3.49144377e-02,
        -4.14677896e-02, -3.37047428e-02,  7.31324255e-02,
         4.41837162e-02,  2.55246833e-02, -8.26402567e-03,
        -1.07322913e-02, -4.26243693e-02, -2.84963124e-03,
         7.38558844e-02,  2.27768160e-02,  7.15417031e-04,
         4.36012372e-02,  5.09079620e-02,  6.38482645e-02,
        -2.73155235e-02, -6.55021295e-02, -7.69265369e-02,
         3.55171524e-02,  9.60493833e-02,  2.18195915e-02,
         1.20154563e-02, -1.17863705e-02, -4.57927678e-03,
        -8.58035777e-03,  3.37150842e-02,  2.31918301e-02,
        -7.58325756e-02, -5.23878783e-02,  4.53934036e-02,
        -3.80785689e-02, -3.34904902e-02,  9.20352861e-02,
         2.87688710e-02, -3.33817154e-02, -1.95852038e-03,
        -3.04564543e-04, -1.70499161e-02,  2.85335835e-02,
        -8.81096721e-02, -4.02253196e-02, -4.00093421e-02,
        -1.03193298e-02, -2.51968615e-02,  2.14093346e-02,
         1.31045252e-01, -5.29632434e-34, -1.09651744e-01,
         1.29811093e-02,  5.92654850e-03,  4.73506115e-02,
        -8.60297214e-03, -3.67089137e-02,  3.05214822e-02,
         5.53067103e-02, -4.71986160e-02, -1.25119099e-02,
        -1.15366362e-01,  9.08003096e-03,  1.07346460e-01,
        -4.94735017e-02, -1.34290410e-02, -4.61562686e-02,
         2.45320518e-02,  9.45077185e-03,  2.04323940e-02,
        -3.99918444e-02, -4.67825644e-02,  2.21171658e-02,
        -4.58187163e-02, -8.13272782e-03, -7.65672605e-03,
         1.92284733e-02,  4.85845283e-02, -2.55902577e-02,
         1.61541475e-03, -1.37180313e-02,  9.67307854e-03,
         7.36412732e-03,  1.14088394e-02,  1.28853485e-01,
         7.71837123e-03,  7.06362575e-02,  2.54452117e-02,
         4.06524017e-02,  2.44039316e-02,  1.43776732e-02,
        -6.00932911e-02,  7.38180578e-02, -2.44700890e-02,
         8.98901075e-02,  3.17054405e-03,  1.01834461e-01,
         4.17742357e-02, -5.95177822e-02, -3.23181823e-02,
         3.80938649e-02,  1.21155614e-02, -4.07834314e-02,
         2.84823105e-02,  4.90988642e-02, -9.35709849e-03,
         6.50074333e-02,  7.23532140e-02, -1.67793669e-02,
        -8.22416972e-03, -1.61573142e-02,  5.96225522e-02,
        -3.36083844e-02,  2.12108362e-02, -6.06090836e-02,
         1.54377624e-01, -7.24146515e-02, -3.77271920e-02,
        -3.26890163e-02, -1.80383108e-03, -1.01960031e-02,
        -1.60680653e-03, -6.91846907e-02,  8.28444883e-02,
         9.88839865e-02,  3.45464004e-03, -9.90247726e-02,
        -3.52827385e-02, -7.13178664e-02, -4.96000424e-02,
        -3.43954451e-02, -8.13042298e-02,  4.81447689e-02,
         5.00684697e-03, -2.21499391e-02, -5.60057051e-02,
         1.00067044e-02, -3.59794013e-02,  1.06184326e-01,
        -4.54196706e-02,  7.16393813e-02, -2.36773398e-02,
         9.98144317e-03,  2.73602400e-02,  1.05985470e-01,
         4.60163541e-02,  9.59028076e-34, -1.12306967e-01,
         2.78912019e-02, -3.35900560e-02,  5.39242513e-02,
        -2.22291294e-02,  1.53769208e-02,  3.10411677e-02,
         3.39011140e-02,  7.43167028e-02,  3.42470892e-02,
        -3.35051771e-03, -2.05350723e-02, -3.62370089e-02,
         2.29334179e-02, -3.01991776e-02, -1.00819893e-01,
         3.29194479e-02,  6.77542835e-02,  1.35645522e-02,
        -5.20543614e-03, -6.58158660e-02,  9.54550877e-02,
        -1.34039139e-02,  1.53885512e-02, -7.22936317e-02,
         9.67836231e-02, -8.08119923e-02, -4.53454908e-03,
        -6.42011613e-02, -4.99278493e-02,  4.64197658e-02,
         2.21341085e-02,  3.13109271e-02,  9.13568512e-02,
        -4.61120307e-02, -1.02761127e-01,  3.04416139e-02,
         5.09876013e-02,  6.70140535e-02,  1.04043074e-02,
         1.63533594e-02,  3.92030925e-02,  2.17153467e-02,
         5.36603481e-02,  3.62809673e-02, -4.22140211e-02,
        -2.47226916e-02,  1.90311745e-02,  3.61724049e-02,
         6.37021363e-02, -3.21583287e-03, -8.50391854e-03,
         3.94655950e-02,  9.02653951e-03,  1.93095934e-02,
         6.60718158e-02,  1.02694724e-02, -4.43853661e-02,
        -1.56523362e-02, -1.55714136e-02,  1.32904546e-02,
        -1.16108358e-02,  4.21832055e-02, -5.44776656e-02,
         1.29237235e-01, -2.25756839e-02,  5.26203848e-02,
        -1.58436671e-02,  9.33165103e-02,  6.38026325e-03,
        -9.36162844e-03, -6.08875677e-02, -3.27307843e-02,
        -3.44816893e-02,  3.29973884e-02, -4.79391851e-02,
        -9.81301069e-02,  2.91164778e-02, -2.70903260e-02,
         1.81867052e-02, -1.73860416e-02, -4.40371260e-02,
        -7.97002316e-02,  3.01647354e-02, -6.35261163e-02,
         1.25962934e-02,  8.50250125e-02, -4.58910652e-02,
         5.81017435e-02, -2.71001812e-02,  8.42775926e-02,
        -4.09972891e-02, -3.37656364e-02,  1.02088312e-02,
        -2.54193190e-02, -1.40610315e-08,  4.94446792e-02,
        -9.04356763e-02, -6.06710128e-02,  8.29529464e-02,
        -3.29032503e-02,  4.14909944e-02,  9.99591127e-03,
         6.96138898e-03,  3.99230979e-03, -3.24333012e-02,
        -3.14656869e-02, -5.33161573e-02, -3.80913652e-02,
         1.62077062e-02,  2.45778318e-02, -7.26419538e-02,
        -6.56893551e-02, -8.23131278e-02, -8.00501034e-02,
        -5.36648966e-02,  5.60894720e-02, -1.10913068e-02,
         9.62207268e-04, -1.22690305e-01, -5.13836741e-02,
         9.96701978e-03,  1.00696459e-02,  1.07073084e-01,
         1.19758314e-02,  1.00423731e-02, -6.28261939e-02,
        -7.49697238e-02, -6.34074211e-03, -2.72201486e-02,
        -1.28096223e-01, -2.62459852e-02, -1.81464404e-02,
        -9.85360146e-02, -3.02990433e-02, -4.02614810e-02,
         9.94291157e-02,  5.35999872e-02,  2.74899881e-02,
        -5.53681934e-03,  8.43571126e-02,  8.35162029e-02,
         3.74304838e-02,  7.11937472e-02,  2.98903231e-02,
         2.32728384e-02, -3.62112150e-02,  6.20539598e-02,
         2.15148423e-02,  5.19732274e-02,  1.45337712e-02,
        -4.60966192e-02,  5.02554663e-02, -7.27027729e-02,
         2.92779021e-02,  5.62662892e-02, -3.86354811e-02,
         1.53831905e-02, -6.23094812e-02, -2.77466271e-02]], dtype=float32)

In [54]:
X = filtered_embeddings
y= df_non_legacy['target_label']

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

                     precision    recall  f1-score   support

     Critical Error       0.94      1.00      0.97        46
              Error       1.00      0.94      0.97        52
        HTTP Status       1.00      1.00      1.00       294
     Resource Usage       1.00      1.00      1.00        50
     Security Alert       1.00      1.00      1.00       120
System Notification       1.00      1.00      1.00       115
        User Action       1.00      1.00      1.00        14

           accuracy                           1.00       691
          macro avg       0.99      0.99      0.99       691
       weighted avg       1.00      1.00      1.00       691

In [ ]:
import joblib
#joblib.dump(clf, 'models/log_classifier.joblib')

['models/log_classifier.joblib']